{% set name = "xorg-libXdamage" %}
{% set version = "1.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/lib/{{ name.split('-')[1] }}-{{ version }}.tar.xz
  sha256: 127067f521d3ee467b97bcb145aeba1078e2454d448e8748eb984d5b397bde24

build:
  number: 0
  # xorg-libxdmcp, libxcb, libx11, libice aren't available on Windows because their dependencies clash with m2/msys2 and mingw64/ucrt64 toolchains.
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower) }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - pkg-config
    - gnuconfig
    - make
    - libtool
    - autoconf
    - automake
  host:
    - xorg-xorgproto {{ xorg_xorgproto }}
    - xorg-libx11 {{ xorg_libx11 }}
    - xorg-libxext {{ xorg_libxext }}
    - xorg-libxfixes {{ xorg_libxfixes }}
    - xorg-util-macros ==1.20.2

test:
  commands:
    - test -f $PREFIX/lib/libXdamage.dylib  # [osx]
    - test -f $PREFIX/lib/libXdamage.so     # [linux]

about:
  home: https://www.x.org/
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libxdamage
  doc_url: https://gitlab.freedesktop.org/xorg/lib/libxdamage
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The X.org X11 Damage Extension library.
  description: The X.org X11 Damage Extension library.

extra:
  recipe-maintainers:
    - zklaus
